
source 'https://cdn.cocoapods.org'
source 'https://github.com/WZLYiOS/WZPodSpecs.git'

platform :ios,'10.0'
use_frameworks!

target 'WZRefresh_Example' do
  pod 'WZRefresh', :path => '../'

  pod 'WZEmptyView'
  target 'WZRefresh_Tests' do
    inherit! :search_paths

    
  end
end
