
source 'https://cdn.cocoapods.org'
source 'https://code.aliyun.com/wzlyios/WZLYPodSpecs.git'

platform :ios,'13.0'
use_frameworks!

target 'WZRefresh_Example' do
  pod 'WZRefresh', :path => '../'

  pod 'WZEmptyView'
  pod 'SnapKit'
  target 'WZRefresh_Tests' do
    inherit! :search_paths

    
  end
end
